### ISSUE TITLE
rustfmt producing invalid code

### ISSUE THREAD

**Issue by mlafeldt** [rust-lang-nursery/rustfmt#1658]
rustfmt 0.8.4 and current HEAD will format this:

```rust
                assert!(Syscheck::new(&mut vec![String::from("one"), String::from("two")]).is_err());
```

To this code, which can't be compiled:

```rust
                assert!(
                    Syscheck::new(&mut vec![String::from("one"), String::from("two")]).is_err(),
                );
```

We're using the config at https://github.com/rust-lang-nursery/rustfmt/blob/master/rfc-rustfmt.toml

**Comment by topecongiro** [comment]
I think this is fixed on the current master. It may exceed max width, but will not produce invalid code.

**Comment by mlafeldt** [comment]
I installed current master (272b0b6f) via Cargo and it did not fix the issue though.

**Comment by topecongiro** [comment]
Unfortunately I could not reproduce the issue with my environment. Are you sure you are using the rustfmt from the current master? `rustfmt --version` should give something like `0.8.4-nightly (272b0b6 2017-06-12)`. Either way, I added commit to #1654 and it should fix this issue.

**Comment by topecongiro** [comment]
Closing since this if fixed on the current master.

**Comment by mlafeldt** [comment]
True! Thank you.
