### ISSUE TITLE
No fixpoint when rewriting function call with inner comment

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1747]
E.g.
```rust
foo(xxxxxxx, xxxxxxxx /* inline comment */, y /* sup */);
```
```rust
foo(
    xxxxxxx,
    xxxxxxxx, // inline comment
    y, /* sup */
);

**Comment by scampi** [comment]
Do you have a working example @topecongiro ?
The one from the description gets normalised:

```diff
 fn bar() {
-    foo(xxxxxxx, xxxxxxxx /* inline comment */, y /* sup */);
+    foo(
+        xxxxxxx, xxxxxxxx, // inline comment
+        y,        // sup
+    );
 }
```

**Comment by scampi** [comment]
Although the spacing before `// sup` is strange...

**Comment by topecongiro** [comment]
Yeah looks like the original issue is fixed.

**Comment by scampi** [comment]
@topecongiro I have renamed the issue to better reflect the new problem

**Comment by ytmimi** [comment]
This is still reproducible with the current master`rustfmt 1.5.1-nightly (0cb294f0 2022-07-12)` when setting `normailze_comments=true`

**input**
```rust
fn main() {
    foo(xxxxxxx, xxxxxxxx /* inline comment */, y /* sup */);
}
```
**output**
```rust
fn main() {
    foo(
        xxxxxxx, xxxxxxxx, // inline comment
        y,        // sup
    );
}
```

Doing some testing, and forcing [`try_overflow_last_item`](https://github.com/rust-lang/rustfmt/blob/a7bf0090347d8523dd62c0508a4c8413cdba099a/src/overflow.rs#L609) last item to return a `DefinitiveListTactic::Vertical` produces the following output:

```
fn main() {
    foo(
        xxxxxxx,
        xxxxxxxx, // inline comment
        y,        // sup
    );
}
```

Just a hunch but it seems like the comment alignment is still trying to align the comments even when the `tactic = DefinitiveListTactic::Mixed`, so I'm guessing the issue occurs somewhere when handling post comments in [`write_list`](https://github.com/rust-lang/rustfmt/blob/a7bf0090347d8523dd62c0508a4c8413cdba099a/src/lists.rs#L260).

https://github.com/rust-lang/rustfmt/blob/a7bf0090347d8523dd62c0508a4c8413cdba099a/src/lists.rs#L404-L504

**Comment by ytmimi** [comment]
linking tracking issue for `normalize_comments` #3350
