### ISSUE TITLE
Macro expressions with blocks

### ISSUE THREAD

**Issue by Victor-Savu** [rust-lang-nursery/rustfmt#1764]
This code is formatted correctly:

```rust
macro_rules! testing{
    ($elem:expr => $body:block) => {{
        let res = $body;
        ($elem == res)
    }}
}

fn main() {
    let are_equal = testing!(1+2 => {
        3
    });
    assert!(are_equal);
}
```

`rustfmt` version `0.9.0` adds a line break and messes up block indentation as well:

```rust
    let are_equal =
        testing!(1+2 => {
        3
    });
    assert!(are_equal);
```

This seems to happen when macro patterns match blocks but I haven't investigated much further.
This didn't use to happen in version `0.7.0` as far as I can tell.

**Comment by topecongiro** [comment]
I think this is fixed on the current master. Could you please try it?

**Comment by Victor-Savu** [comment]
Just tried it out.
I installed `rustfmt` as follows:

```bash
cargo install --branch master rustfmt
```

The problem persists. Just for reference, version 0.8.0 wasn't affected so the regression happened at some point afterwards.

**Comment by topecongiro** [comment]
Could you please try `rustfmt-nightly` instead of `rustfmt`? The former should include the fix.

**Comment by topecongiro** [comment]
Closing since this is fixed on the latest `rustfmt-nightly`.
