### ISSUE TITLE
Comment after let exceeds max width

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2198]
#### Input

```rust
fn foo() {
    let file_name =
        format!("{}", self.testpaths.file.display())
        .replace(r"\", "/"); // on windows, translate all '\' path separators to '/'
}
```

#### Output

```rust
fn foo() {
    let file_name = format!("{}", self.testpaths.file.display()).replace(r"\", "/"); // on windows, translate all '\' path separators to '/'
}
```

#### Meta
`0.2.16-nightly (4e04e82 2017-11-28)`

The above example is taken from https://github.com/rust-lang/rust/blob/8937d6a6cfb011d9e1fe6b4a426913dbbf9fd584/src/tools/compiletest/src/runtest.rs#L1007-L1009.

**Comment by Bubblepoint** [comment]
Issue looks solved with `1.4.18-nightly (c1e9b7b8 2020-06-13)`

**Output:**
```rust
fn foo() {
    let file_name = format!("{}", self.testpaths.file.display()).replace(r"\", "/");
    // on windows, translate all '\' path separators to '/'
}
```

**Comment by shulaoda** [comment]
If I understand correctly, this issue has already been resolved — at least in this particular case.

**Comment by ytmimi** [comment]
I can still reproduce the issue described in the original comment with rustfmt 1.8.0-nightly (292865f8d3 2025-10-09).

**Comment by shulaoda** [comment]
> I can still reproduce the issue described in the original comment with rustfmt 1.8.0-nightly ([292865f](https://github.com/rust-lang/rustfmt/commit/292865f8d34ea42f4a18a22906bb9f4bc1d15ee9) 2025-10-09).

I think I misunderstood earlier — when I set max_width to `<70`, it behaves correctly. It seems that the length of the let statement isn’t counted together with the comment, which explains the result.

**Comment by ytmimi** [comment]
@shulaoda when triaging it's best to use the default rustfmt configs unless the issue specifies that certain configs are needed to reproduce the issue.
