### ISSUE TITLE
Running rustfmt in Travis

### ISSUE THREAD

**Issue by orenbenkiki** [rust-lang-nursery/rustfmt#2285]
I've just tried adding `cargo fmt -- --write-mode diff` in Travis, following the example in the README.
 I get the error `This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.`. This happens even when using the nightly rust.

I tried various ways of getting Travis to install/use the right `rustfmt` version. I have seen all sort of other incantations in different projects but none worked for me.

Either I'm doing something wrong...

Or the README example should be improved to describe the correct way to use `rustfmt` in Travis (if it makes a difference, when using nightly, stable, or a specific rust version).

**Comment by nrc** [comment]
You need to install the rustfmt-nightly crate, not the rustfmt crate. I've updated the README.md to fix the `cargo install` command.

**Comment by orenbenkiki** [comment]
I must be doing something wrong then.

My `.travis.yml` looks like this (taken from the updated README):
```yaml
# Rust project
language: rust
cache: cargo

rust:
- 1.21.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt-nightly

script:
- cargo fmt -- --write-mode=diff
- cargo build --verbose
- cargo test --verbose
```

And I still get the error (see https://travis-ci.org/orenbenkiki/loggy/builds/316871482 for example).

**Comment by nrc** [comment]
Hmm, I wonder if your Travis instance has rustfmt pre-installed? (`which rustfmt` is OK)

**Comment by orenbenkiki** [comment]
For investigation purposes, I changed the `.travis.yml` to say:
```yaml
before_script:
- export PATH="$HOME/.cargo/bin:$PATH"
- which rustfmt || true
- rustfmt --version || true
- cargo install --force rustfmt-nightly || true
- which rustfmt || true
- rustfmt --version
```
And I tried building it in Travis with different rust versions. See https://travis-ci.org/orenbenkiki/loggy/builds/317341837 for the full logs. The results were... interesting....?

| Version | Rustfmt Pre-Installed? | Success installing rustfmt-nightly? | Success using rustfmt-nightly? |
| - | - | - | - |
| 1.21.0 | Yes, deprecated version | No, failed to compile | NA |
| 1.22.0 | No(!) | No, failed to compile | NA |
| Stable (1.22.1) | Yes, deprecated version | No, failed to compile | NA |
| Beta (1.23.0-beta.2) | Yes, deprecated version | No, failed to compile | NA |
| Nightly (1.24.0-noghtly) | Yes, deprecated version(!) | Yes | No(!), failed to load libsyntax-....so |

So, batting zero out of 5, for two different reasons:

- It seems like it isn't possible to compile `rustfmt-nightly` unless one is using the nightly version of `rustc`. This sort of makes sense, I guess.

It is possible of course to add tests that restrict using `cargo fmt` and installing `rustfmt` only if using the nightly version of `rustc`. However...

- There is something strange that happens when using nightly (the shared `libsyntax` library used by `rustfmt` fails to load). This might be a transient issue - it is the nightly version we are talking about after all, occasional breaks are expected.

This highlights the point that there is a common practice of allowing failures when building a package with the nightly version; such builds are mainly for informational purposes to direct future-proofing the packages against future releases. In particular such builds are not used as a gateway for accepting/rejecting new commits. So restricting `cargo fmt` only to nightly builds would be missing the whole point.

Ideally what we want is the ability to run `rustfmt-nightly` when using arbitrary `rustc` versions. One possible solution would be to provide a statically-linked (Linux) binary one could download directly into `~/.cargo/bin`, instead of using `cargo` - at least until things stabilize. Or, maybe we could ask the Travis people to pre-install the nightly version instead of the deprecated version...?

Either way, right now it seems that using `cargo fmt` in Travis should be avoided...?

**Comment by djc** [comment]
It would be very nice if there was a way to only run `rustfmt` (the nightly version) for `nightly` versions of rust. I don't the magic incantations for that, but perhaps that would be a good start?

**Comment by Marwes** [comment]
@orenbenkiki You are having trouble because first, as you noticed you need a nightly rust and cargo to actually install rustfmt-nightly. You can fix this to make it install on any version off rust by explicitly telling `cargo` to run using nightly.

```sh
# You probably also need to install nightly
rustup install nightly
cargo +nightly install --force rustfmt-nightly
```

The issue where it fails to load libsyntax is due to a similar issue. Rustfmt will link against dynamic libraries distributed through your rust installation. So if you have a different rustc as the default set by `rustup` then rustfmt will be unable to find the library. You can work around this problem by running `rustfmt` through rustup with and explicitly set the version. This way `rustup` sets the correct paths and rustfmt finds the libraries.


```sh
rustup run nightly rustfmt
```

**Comment by orenbenkiki** [comment]
Thanks! Doing the following works in Travis:
```
rustup install nightly
cargo +nightly install --force rustfmt-nightly
cargo +nightly fmt -- --write-mode diff
```
Using `install --force` means that this ignores the cargo cache set up by Travis. A small price to pay, I guess.

At any rate, if this is the recommended incantation, the README needs to be updated accordingly.

**Comment by davidalber** [comment]
@topecongiro: I believe #2411 also closes this issue.

**Comment by topecongiro** [comment]
@davidalber Thank you for triaging!

**Comment by brokenthorn** [comment]
> You need to install the rustfmt-nightly crate, not the rustfmt crate. I've updated the README.md to fix the `cargo install` command.

The only way I got rustfmt to install was to install it with `cargo install rustfmt-nightly --force` but why is there a rustup component with stable for it as well, because they seem to conflict!? And the component is gone with nightly. It's not available anymore. I dug a bit about this latter issue and might be a CI problem but now I think it's being deprecated as a Rustup component, as in it's not managed that way anymore. Is this right?

```
➜  ~ rustup show
Default host: x86_64-apple-darwin

nightly-x86_64-apple-darwin (default)
rustc 1.32.0-nightly (4a45578bc 2018-12-07)
```

**Comment by orenbenkiki** [comment]
Note that if one restricts CI builds to use Rust 1.31.0 or higher, then there's no real reason to invoke the nightly `rustfmt` any more. Calling `cargo fmt -- --check` should "just work".

If one is interested in building using older versions of Rust (lower than 1.31.0), then this issue still stands.

The README should probably say something along these lines...

**Comment by orenbenkiki** [comment]
It seems that using `cargo` to install `rustfmt` is deprecated, and that one should use `rustup component add rustfmt-nightly` instead - see #4776. Waiting for resolution there...

**Comment by orenbenkiki** [comment]
Running `rustup toolchain install --allow-downgrade nightly -c rustfmt` inside a nightly build in Travis will downgrade the nightly toolchain version to the latest one that can compile `rustfmt`. This will ensure that builds that use `rustfmt` will have a chance of succeeding, but gives up on running the very-bleeding-edge-latest nightly. Tradeoff.

It is also technically possible to download the binaries of the latest `rustfmt` version (for the main target platforms) and manually install them to fool `cargo` into using them as if `rustfmt` was properly installed, but the process is involved and there's no stable automation script for it.

Finally, `cargo make` had an option for skipping the `rustfmt` steps while running CI buils in nightly, then one could rely on these steps being run in the stable build, and just let the nightly build skip them.  This depends on whether https://github.com/sagiegurari/cargo-make/issues/538 is accepted and implemented.
