### ISSUE TITLE
Master broken?

### ISSUE THREAD

**Issue by max-sixty** [rust-lang-nursery/rustfmt#2957]
https://travis-ci.org/rust-lang-nursery/rustfmt/jobs/419970670

This fails on a simple linux build, not only on the integration tests.

Specifically:

```
   Compiling rustc-ap-rustc_errors v235.0.0
error: found removed `do catch` syntax
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-syntax-235.0.0/parse/parser.rs:1762:43
     |
1762 |             let pat_arg: PResult<'a, _> = do catch {
     |                                           ^^
     |
     = help: Following RFC #2388, the new non-placeholder syntax is `try`
error: aborting due to previous error
error: Could not compile `rustc-ap-syntax`.
```

Weirdly, I can't recreate locally - any idea for how this could happen?

It works fine on MacOS. I tried building on Linux to ensure that wasn't creating any diff, and that also worked (`docker run -it -v (pwd):(pwd) -w (pwd) rust cargo test`)

**Comment by topecongiro** [comment]
Should be fixed by https://github.com/rust-lang-nursery/rustfmt/pull/2964.

**Comment by zachlute** [comment]
#2965 is a better version of that change, but still failing some tests.
