### ISSUE TITLE
windows line endings `\r\n` are mutated to `\n`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rustfmt#42]
I'd fix it myself, but I don't know what the best way would be.

There are also other things like adding a `\n` at the end of file.

What do you think about doing it git-style. Reading files skips `\r`, but sets a flag if it encounters an `\r`. Writing back adds `\r` before every `\n`. This would prevent any fancy conditionals inside the logic code.

**Comment by nrc** [comment]
I think it should be configurable to use either `\n` or `\r\n` or preserve the file's formatting (i.e., the procedure you suggest). I suggest this because I've worked on projects (Firefox) which mandate never using windows line endings.

**Comment by oli-obk** [comment]
rustfmt doesn't have any command line arguments yet as far as I can see in the code. So I'm not sure how you want this specified. Maybe as a cfg-option? http://doc.rust-lang.org/rustc/session/config/struct.Options.html

**Comment by nrc** [comment]
For now, just as a global variable, there's another issue open for adding an actual config file.

**Comment by oli-obk** [comment]
apparently libsyntax removes `\r` before rustfmt ever sees them...

**Comment by marcusklaas** [comment]
This has been resolved, right?

**Comment by oli-obk** [comment]
there has been some work towards it, but not fully resolved. I'll check next week what the current state is

**Comment by cassiersg** [comment]
We have an option with two possibilities : Unix or Windows. There is not auto-detection feature now.

**Comment by cyplo** [comment]
Hi ! Does the referenced merge solve this issue ?

**Comment by nrc** [comment]
There's still no auto-detection feature, but I think the current array of options are good enough to close this issue.
